import type { NarrativeStructure } from "./types.js";

export const herosJourney: NarrativeStructure = {
  name: "Hero's Journey",
  description: "A mythic transformation arc for characters who leave a known world, face ordeal, and return changed.",
  beats: [
    {
      id: "ordinary-world",
      name: "Ordinary World",
      description: "Show the hero's familiar life and the lack that makes change necessary.",
      type: "setup",
      transitions: [{ to: "call-to-adventure", weight: 1 }],
    },
    {
      id: "call-to-adventure",
      name: "Call to Adventure",
      description: "An invitation or disruption points the hero toward the unknown.",
      type: "setup",
      transitions: [
        { to: "refusal-of-call", weight: 0.75 },
        { to: "meeting-mentor", weight: 0.25 },
      ],
    },
    {
      id: "refusal-of-call",
      name: "Refusal of the Call",
      description: "Fear, duty, or disbelief makes the hero resist the journey.",
      type: "conflict",
      transitions: [{ to: "meeting-mentor", weight: 1 }],
    },
    {
      id: "meeting-mentor",
      name: "Meeting the Mentor",
      description: "A guide, tool, warning, or blessing prepares the hero to cross over.",
      type: "setup",
      transitions: [
        { to: "supernatural-aid", weight: 0.7 },
        { to: "crossing-threshold", weight: 0.3 },
      ],
    },
    {
      id: "supernatural-aid",
      name: "Supernatural Aid",
      description: "The mentor's help becomes a tangible token, skill, blessing, or map.",
      type: "setup",
      transitions: [{ to: "crossing-threshold", weight: 1 }],
    },
    {
      id: "crossing-threshold",
      name: "Crossing the Threshold",
      description: "The hero commits and enters a world with new rules.",
      type: "rising",
      transitions: [
        { to: "belly-of-the-whale", weight: 0.55 },
        { to: "tests-allies-enemies", weight: 0.45 },
      ],
    },
    {
      id: "belly-of-the-whale",
      name: "Belly of the Whale",
      description: "The hero is swallowed by the new world and cannot simply go back.",
      type: "conflict",
      transitions: [{ to: "tests-allies-enemies", weight: 1 }],
    },
    {
      id: "tests-allies-enemies",
      name: "Tests, Allies, and Enemies",
      description: "Trials reveal the new world and sort helpers from threats.",
      type: "rising",
      transitions: [
        { to: "temptation", weight: 0.25 },
        { to: "approach-inmost-cave", weight: 0.55 },
        { to: "tests-allies-enemies", weight: 0.2 },
      ],
    },
    {
      id: "temptation",
      name: "Temptation",
      description: "A seductive shortcut or comfort tests whether the hero still belongs to the old self.",
      type: "conflict",
      transitions: [{ to: "approach-inmost-cave", weight: 1 }],
    },
    {
      id: "approach-inmost-cave",
      name: "Approach to the Inmost Cave",
      description: "The hero nears the central danger and chooses what must be risked.",
      type: "rising",
      transitions: [
        { to: "atonement", weight: 0.45 },
        { to: "ordeal", weight: 0.55 },
      ],
    },
    {
      id: "atonement",
      name: "Atonement",
      description: "The hero confronts authority, inheritance, guilt, or the old law before the ordeal.",
      type: "conflict",
      transitions: [{ to: "ordeal", weight: 1 }],
    },
    {
      id: "ordeal",
      name: "Ordeal",
      description: "A symbolic death, defeat, or deepest fear forces transformation.",
      type: "climax",
      transitions: [{ to: "reward", weight: 1 }],
    },
    {
      id: "reward",
      name: "Reward",
      description: "The hero claims knowledge, treasure, reconciliation, or power.",
      type: "falling",
      transitions: [{ to: "road-back", weight: 1 }],
    },
    {
      id: "road-back",
      name: "The Road Back",
      description: "Consequences pursue the hero toward a final commitment.",
      type: "falling",
      transitions: [
        { to: "magic-flight", weight: 0.45 },
        { to: "resurrection", weight: 0.55 },
      ],
    },
    {
      id: "magic-flight",
      name: "Magic Flight",
      description: "The return becomes a chase, escape, or urgent flight from the consequences of victory.",
      type: "falling",
      transitions: [{ to: "resurrection", weight: 1 }],
    },
    {
      id: "resurrection",
      name: "Resurrection",
      description: "A final test proves the hero's change under the highest stakes.",
      type: "climax",
      transitions: [{ to: "return-with-elixir", weight: 1 }],
    },
    {
      id: "return-with-elixir",
      name: "Return with the Elixir",
      description: "The hero brings change back to the community or the self.",
      type: "resolution",
      transitions: [{ to: "ordinary-world", weight: 1 }],
    },
  ],
  constraints: [
    {
      type: "ordering",
      beforeBeat: "ordinary-world",
      afterBeat: "crossing-threshold",
      severity: "blocking",
      description: "The known world must be established before the hero crosses into the unknown.",
    },
    {
      type: "ordering",
      beforeBeat: "ordeal",
      afterBeat: "reward",
      severity: "blocking",
      description: "The reward only matters after the ordeal has changed the hero.",
    },
    {
      type: "reference",
      ifBeat: "meeting-mentor",
      thenBeat: "resurrection",
      relation: "must_also_occur",
      severity: "warning",
      description: "The mentor's gift or lesson should echo in the final test.",
    },
  ],
};
