import type { NarrativeStructure } from "./types.js";

export const saveTheCat: NarrativeStructure = {
  name: "Save the Cat",
  description: "A fifteen-beat screenplay-oriented structure for tightly paced transformation and genre promise.",
  beats: [
    {
      id: "opening-image",
      name: "Opening Image",
      description: "A snapshot of the protagonist's life before change.",
      type: "setup",
      transitions: [{ to: "theme-stated", weight: 1 }],
    },
    {
      id: "theme-stated",
      name: "Theme Stated",
      description: "Someone names the lesson the protagonist cannot yet understand.",
      type: "setup",
      transitions: [{ to: "set-up", weight: 1 }],
    },
    {
      id: "set-up",
      name: "Set-Up",
      description: "Lay out the hero's world, wants, flaws, and supporting cast.",
      type: "setup",
      transitions: [{ to: "catalyst", weight: 1 }],
    },
    {
      id: "catalyst",
      name: "Catalyst",
      description: "A life-changing event knocks the story out of balance.",
      type: "conflict",
      transitions: [{ to: "debate", weight: 1 }],
    },
    {
      id: "debate",
      name: "Debate",
      description: "The hero hesitates, weighs risk, and resists the new direction.",
      type: "conflict",
      transitions: [
        { to: "break-into-two", weight: 0.9 },
        { to: "debate", weight: 0.1 },
      ],
    },
    {
      id: "break-into-two",
      name: "Break into Two",
      description: "The hero makes the choice that launches the main story world.",
      type: "rising",
      transitions: [{ to: "b-story", weight: 1 }],
    },
    {
      id: "b-story",
      name: "B Story",
      description: "A relationship or subplot carries the theme in emotional form.",
      type: "rising",
      transitions: [{ to: "fun-and-games", weight: 1 }],
    },
    {
      id: "fun-and-games",
      name: "Fun and Games",
      description: "Deliver the premise's entertaining promise while pressure mounts underneath.",
      type: "rising",
      transitions: [
        { to: "midpoint", weight: 0.8 },
        { to: "fun-and-games", weight: 0.2 },
      ],
    },
    {
      id: "midpoint",
      name: "Midpoint",
      description: "A false win or loss raises stakes and changes the hero's tactics.",
      type: "climax",
      transitions: [{ to: "bad-guys-close-in", weight: 1 }],
    },
    {
      id: "bad-guys-close-in",
      name: "Bad Guys Close In",
      description: "External pressure and internal flaws squeeze the hero from both sides.",
      type: "rising",
      transitions: [{ to: "all-is-lost", weight: 1 }],
    },
    {
      id: "all-is-lost",
      name: "All Is Lost",
      description: "The hero suffers symbolic death and appears to lose the goal.",
      type: "falling",
      transitions: [{ to: "dark-night-of-the-soul", weight: 1 }],
    },
    {
      id: "dark-night-of-the-soul",
      name: "Dark Night of the Soul",
      description: "The hero processes the loss and finally grasps the theme.",
      type: "falling",
      transitions: [{ to: "break-into-three", weight: 1 }],
    },
    {
      id: "break-into-three",
      name: "Break into Three",
      description: "A new synthesis of A story and B story points to the solution.",
      type: "rising",
      transitions: [{ to: "finale", weight: 1 }],
    },
    {
      id: "finale",
      name: "Finale",
      description: "The hero executes the transformed plan and resolves the central conflict.",
      type: "resolution",
      transitions: [{ to: "final-image", weight: 1 }],
    },
    {
      id: "final-image",
      name: "Final Image",
      description: "A closing snapshot mirrors the opening and proves change.",
      type: "resolution",
      transitions: [{ to: "opening-image", weight: 1 }],
    },
  ],
  constraints: [
    {
      type: "ordering",
      beforeBeat: "opening-image",
      afterBeat: "final-image",
      severity: "warning",
      description: "The final image should intentionally mirror or invert the opening image.",
    },
    {
      type: "ordering",
      beforeBeat: "theme-stated",
      afterBeat: "dark-night-of-the-soul",
      severity: "blocking",
      description: "The stated theme should be tested before the hero internalizes it.",
    },
    {
      type: "reference",
      ifBeat: "b-story",
      thenBeat: "break-into-three",
      relation: "must_also_occur",
      severity: "warning",
      description: "The B story should contribute to the Act Three solution.",
    },
  ],
};
